const dataobj = [
  {
    Id: 1,
    title: "Acura NSX",
    categorie: "sport",
    img: "./images/car-sedan3.png",
    price: "99.00",

    page: 1,
  },
  {
    Id: 2,
    title: "BMW X5",
    categorie: "suv",
    img: "./images/car-sedan2.png",
    price: "89.00",

    page: 1,
  },
  {
    Id: 3,
    title: "Toyota Camry",
    categorie: "sedan",
    img: "./images/car-sedan1.png",
    price: "79.00",

    page: 1,
  },
  {
    Id: 4,
    title: "Porsche 9112",
    categorie: "sport",
    img: "./images/car-sport2.png",
    price: "109.00",
    page: 1,
  },
  {
    Id: 5,
    title: "Jeep Wrangler",
    categorie: "suv",
    img: "./images/car-suv2.png",
    price: "79.00",

    page: 1,
  },
  {
    Id: 6,
    title: "Honda Accord",
    categorie: "sedan",
    img: "./images/car-sedan2.png",
    price: "69.00",

    page: 1,
  },
  {
    Id: 7,
    title: "Ford Mustangs",
    categorie: "sport",
    img: "./images/car-sport3.png",
    price: "89.00",
    page: 2,
  },
  {
    Id: 8,
    title: "Tesla Model Xx",
    categorie: "suv",
    img: "./images/car-suv3.png",
    price: "109.00",
    page: 2,
  },
  {
    Id: 9,
    title: "Nissan Altimas",
    categorie: "sedan",
    img: "./images/car-sedan3.png",
    price: "79.00",
    page: 2,
  },
  {
    Id: 10,
    title: "Acura NSaX",
    categorie: "sport",
    img: "./images/car-sport1.png",
    price: "99.00",
    page: 2,
  },
  {
    Id: 11,
    title: "BMW Xd5",
    categorie: "suv",
    img: "./images/car-suv1.png",
    price: "89.00",
    page: 2,
  },
  {
    Id: 12,
    title: "Toyota Camrys",
    categorie: "sedan",
    img: "./images/car-sedan1.png",
    price: "79.00",
    page: 2,
  },
  {
    Id: 13,
    title: "Porsche 911s",
    categorie: "sport",
    img: "./images/car-sport2.png",
    price: "109.00",
    page: 3,
  },
  {
    Id: 14,
    title: "Jeep Wranglers",
    categorie: "suv",
    img: "./images/car-suv2.png",
    price: "79.00",
    page: 3,
  },
  {
    Id: 15,
    title: "Honda Accords",
    categorie: "sedan",
    img: "./images/car-sedan2.png",
    price: "69.00",
    page: 3,
  },
  {
    Id: 16,
    title: "Ford Mustangs",
    categorie: "sport",
    img: "./images/car-sport3.png",
    price: "89.00",
    page: 3,
  },
  {
    Id: 17,
    title: "Tesla Model XD",
    categorie: "suv",
    img: "./images/car-suv3.png",
    price: "109.00",
    page: 3,
  },
  {
    Id: 18,
    title: "Nissan Altimas",
    categorie: "sedan",
    img: "./images/car-sedan3.png",
    price: "79.00",
    page: 3,
  },
];
localStorage.setItem("dataobj", JSON.stringify(dataobj));

// export { dataobj };
export { dataobj };
